version: '3.7'
services:
  web:
    build: .
    container_name: apprisen-client-portal
    init: true
    command: /bin/ash -c "npm rebuild node-sass && ionic serve -l --lab-host=0.0.0.0 --lab-port=8200"
    volumes:
      - .:/usr/apprisen/app
    expose:
      - 8100
      - 8200
    ports:
      - "8100:8100"
      - "8200:8200"